version: '3.1'


services:


   db:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: never
      environment:
         MYSQL_ROOT_PASSWORD: password


   adminer:
      image: adminer
      restart: never
      ports:
         - 8080:8080
